services:
  proxy:
    image: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      # UI
      - target: 80
        published: ${PROXY_UI_PORT?}
      # Stats
      - target: 8080
        published: ${PROXY_STATS_PORT?}
      # visualizer
      - target: 8081
        published: ${PROXY_VISUALIZER_PORT?}
