volumes:
  blockscout-db-data:
  stats-db-data:
  redis-data:
  logs:
  dets:

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
      - CHAIN_ID=${CHAIN_ID?}
      - SUBNETWORK=${SUBNETWORK?}
      - ETHEREUM_JSONRPC_HTTP_URL=${ETHEREUM_JSONRPC_HTTP_URL?}
      - ETHEREUM_JSONRPC_WS_URL=${ETHEREUM_JSONRPC_WS_URL?}
      - ETHEREUM_JSONRPC_TRACE_URL=${ETHEREUM_JSONRPC_TRACE_URL?}

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      - NEXT_PUBLIC_NETWORK_ID=${NEXT_PUBLIC_NETWORK_ID?}

      # Kinda sucks. Why does this communicate via the host network?
      - NEXT_PUBLIC_STATS_API_HOST=http://localhost:${PROXY_STATS_PORT}
      - NEXT_PUBLIC_VISUALIZE_API_HOST=http://localhost:${PROXY_VISUALIZER_PORT}
      - NEXT_PUBLIC_API_HOST=localhost:${PROXY_UI_PORT}
      - NEXT_PUBLIC_APP_HOST=localhost:${PROXY_UI_PORT}

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  smart-contract-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    depends_on:
      - backend
      - frontend
  
  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    platform: linux/amd64

